### ISSUE TITLE
Address Initial Feedback

### ISSUE THREAD

**Issue by ansermino** [ChainSafe/chainbridge-substrate#5]
- [x] Rename Validators to Relayers (should happen accross the board)
- [x] Require root to whitelist chain, change validators and change EmitterAddress
- [x] Add ability for root to change threshold
- [x] EmitterAddress should be updated to better suit the notion of a chain ID (add to genesis)
- [ ] Remove need to store AccountId of voters by indexing them instead (see #8)
- [x] Compute proposal hash on-chain -- maybe concat 2 separate hashes to make this easier
- [x] Remove usages of unwrap
- [ ] Prune state; remove proposal after completion (part of block prod?) (see #8)
- [x] Update vote against condition: votes against > validator set size - threshold
  - [x] Add validator count
  - [x] Update condition

### Tests
- [x] Test genesis config - https://github.com/centrifuge/substrate-pallet-multi-account/blob/a80ed7a071a449681ef57c95fa13b06b302a66f2/src/lib.rs#L849-L864
- [ ] Test events firing (see #7)
